apiVersion: v1
kind: Service
metadata:
  name: {{ include "opentelemetry-collector.fullname" . }}
  labels:
    {{- include "opentelemetry-collector.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- if and (index .Values.ports "otlp-http") ((index .Values.ports "otlp-http" ).enabled) }}
    {{- with (index .Values.ports "otlp-http") }}
    - name: otlp-http
      port: {{ .servicePort }}
      targetPort: otlp-http
      protocol: {{ .protocol }}
    {{- end }}
    {{- end }}
    {{- range $key, $port := .Values.ports }}
    {{- if and $port.enabled (ne $key "otlp-http") }}
    - name: {{ $key }}
      port: {{ $port.servicePort }}
      targetPort: {{ $key }}
      protocol: {{ $port.protocol }}
    {{- end }}
    {{- end }}
  selector:
    {{- include "opentelemetry-collector.selectorLabels" . | nindent 4 }}
