apiVersion: v2
name: opentelemetry-collector
description: OpenTelemetry Collector for Honeycomb
type: application
version: 0.1.0
appVersion: 0.4.0
keywords:
  - observability
  - tracing
home: https://honeycomb.io
sources:
  - https://github.com/honeycombio/opentelemetry-collector
  - https://github.com/honeycombio/opentelemetry-collector-contrib
icon: https://www.honeycomb.io/wp-content/themes/honeycomb/assets/img/logo.svg
maintainers:
  - name: puckpuck
    email: pierre@honeycomb.io
