{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "honeycomb.agent.fullname" . }}
  labels:
    {{- include "honeycomb.agent.labels" . | nindent 4 }}
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - list
      - watch
{{- end }}
