{{- if and .Values.rbac.create .Values.events.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "honeycomb.events.fullname" . }}
  labels:
  {{- include "honeycomb.events.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "honeycomb.events.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "honeycomb.fullname" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}