{{- if and .Values.rbac.create .Values.events.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "honeycomb.events.fullname" . }}
  labels:
    {{- include "honeycomb.events.labels" . | nindent 4 }}
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
rules:
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - list
      - watch
  {{- end }}
