{{- if and .Values.rbac.create .Values.metrics.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "honeycomb.metrics.fullname" . }}
  labels:
    {{- include "honeycomb.metrics.labels" . | nindent 4 }}
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
rules:
  - apiGroups:
      - ""
    resources:
      - events
      - namespaces
      - nodes
      - nodes/stats
      - pods
      - services
    verbs:
      - get
      - list
      - watch
  - nonResourceURLs: ["/metrics"]
    verbs:
      - get
  {{- end }}
