{{- if .Values.metrics.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "honeycomb.metrics.fullname" . }}
  labels:
    {{- include "honeycomb.metrics.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "honeycomb.metrics.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.metrics.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "honeycomb.metrics.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "honeycomb.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.metrics.podSecurityContext | nindent 8 }}
      containers:
        - name: heapster
          securityContext:
            {{- toYaml .Values.metrics.securityContext | nindent 12 }}
          image: "{{ .Values.metrics.image.repository }}"
          imagePullPolicy: {{ .Values.metrics.image.pullPolicy }}
          command:
            - /heapster
          args:
            - --source={{ .Values.metrics.source }}
            - --sink=honeycomb:?dataset={{ .Values.metrics.dataset }}
          env:
            - name: HONEYCOMB_WRITEKEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "honeycomb.fullname" . }}
                  key: api-key
          resources:
            {{- toYaml .Values.metrics.resources | nindent 12 }}
      {{- with .Values.metrics.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.metrics.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.metrics.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end}}
